kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  MOUNT_PATH: {{ .Values.mountPath }}
  FILE: {{ .Values.storeFile }}
  SLACK_CHANNELS: {{ .Values.slackChannels }}
  CLUSTER_NAME: {{ .Values.clusterName }}
