kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  MOUNT_PATH: {{ .Values.mountPath }}
  FILE: {{ .Values.storeFile }}
  SLACK_CHANNELS: {{ required "A JSON array of slack id is required for an env variable" .Values.slackChannels | quote}}
  CLUSTER_NAME: {{ .Values.clusterName }}
