apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  {{- if (.Values.storageClassName)}}
  storageClassName: {{ .Values.storageClassName }}
  {{- end}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi