apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
   slackToken:  {{ required "A base64 encoded Slack API token. .Values.slackToken" .Values.slackToken }}
type: Opaque