# Default values for cloudclock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


mountPath: '/etc/currentState/'
storeFile: 'nodeStore.json'
clusterName: 'internal-24g-cluster'

#The helm parser removes the single quotes so we use the quote function
#in the configmap to put them back

#Change this value if you want a different/more slackchannels. Note: you must add
#the bot to the channel
slackChannels: '["#1575_internal_it"]'


image: 'gcr.io/g-1575-internal-projects/cloudclock:v2'


